### PR TITLE
Make DNS Record form text more helpful

### PR DESCRIPTION
**Pull request by humphd**
In anticipation of having people do user testing on the app, I've added some more instructions/help text to the DNS Record form:

Screenshot 2023-04-03 at 9 12 01 AM
Screenshot 2023-04-03 at 9 14 03 AM

Let me know if you think I can further improve these messages

### CODE REVIEW

**Review by Genne23v — COMMENTED** [review]
Probably my own preference, smaller help texts look nicer to me. Here's the look when you set up help text to `xs` .

Screenshot 2023-04-03 at 11 04 59 AM

**Review by Genne23v — CHANGES_REQUESTED** [review]

**Comment by humphd** [comment]
@Genne23v great suggestions!  I've done both.

**Review by Genne23v — APPROVED** [review]
LGTM!

**Review by Ririio — APPROVED** [review]
I'm going to miss the tooltip, but I noticed my friend wasn't even paying attention to it when looking through the form. Looks great though

**Pull request merged**
