### PR TITLE
Add nginx cert config panel

### PR DESCRIPTION
**Pull request by humphd**
Created another certificate config panel for nginx:

Screenshot 2023-04-06 at 3 07 34 PM

I'm going to need the work from #532 to create the full chain in the UI

### CODE REVIEW

**Review by Eakam1007 — COMMENTED** [review]
Hmm, just realized that these links are not really obvious (that they are links)
image
On hover:
image
Would it be better to do the same thing as on the landing page for these:
image

**Comment by humphd** [comment]
Can we do some global fix for links so they have text decoration/red colour by default?  It's stupid that we have to fix this in a lot of places.

**Comment by Eakam1007** [comment]
> Can we do some global fix for links so they have text decoration/red colour by default? It's stupid that we have to fix this in a lot of places.

We probably can in another issue, cause we don't want the links in the header to be affected for example. Maybe a shared class

**Review by Eakam1007 — APPROVED** [review]
Looks good, we can add the data after the other pr is merged

**Review by Genne23v — APPROVED** [review]
Looks good to me

**Pull request merged**
