### PR TITLE
Build Docker image for linux/amd64, linux/arm64, and linux/arm64/v8

### PR DESCRIPTION
**Pull request by humphd**
This updates CI so that it builds the Docker image for multiple architectures (we only do linux/amd64 right now).  As usual, this is hard to test without actually doing it, so I'll fix bugs after landing.

### CODE REVIEW

**Review by Genne23v — APPROVED** [review]
I don't see any spelling error. It looks good to me.

**Comment by humphd** [comment]
I've added linux/arm64/v8 to the list, since I need that locally for my M1 mac to test the staging deploy.

**Review by dadolhay — APPROVED** [review]
Looks good!

**Review by Genne23v — APPROVED** [review]
Looks good to me

**Pull request merged**
