### PR TITLE
Add documentation about debugging e2e tests

### LINKED ISSUE #295: Include docs on how to understand and debug e2e tests
I am looking at an e2e test failure in #294, see https://github.com/DevelopingSpace/starchart/actions/runs/4348577165

Playwright gives us so much good info and tooling to debug this, and we should document it so others know how to use it.

For example, at the bottom of the GitHub Action, there is a link to download a `playwright-report.zip` file:

Screenshot 2023-03-06 at 6 40 46 PM

This file expands to a folder containing:

1. `index.html`-> a web app that shows all the details of the test runs
2. `data/` -> a folder of videos and `.zip` traces for all of the failed tests

The videos you can play in your browser, and it shows the test running in the browser.  Often you can see what is failing.  However, to get even more detail, you can use the amazing [Trace Viewer](https://playwright.dev/docs/trace-viewer):

```
npx playwright show-trace trace.zip
```

This lets you do all kinds of debugging after the fact, seeing exactly what happened in the test.  It's amazing.

Let's document this so people understand how to use it all.

### PR DESCRIPTION
**Pull request by Eakam1007**
Resolves #295

- Updated the [Playwright wiki page](https://github.com/DevelopingSpace/starchart/wiki/Playwright) to include information about how to debug end to end tests that fail in CI
- Added a section to CONTRIBUTING.md that links to the wiki

### CODE REVIEW

**Review by sfrunza13 — APPROVED** [review]
Maybe also mention that the `https://github.com/DevelopingSpace/starchart/wiki/Playwright` link is also good for learning how to generate tests and use playwright in general and that navigating there is highly encouraged. All of the goods are on that page, since sometimes contributors will have to be writing tests using it.

**Comment by Eakam1007** [comment]
I added a separate section for end to end tests and made the debugging section a sub section

**Review by sfrunza13 — APPROVED** [review]
looks good

**Review by sfrunza13 — APPROVED** [review]

**Review by humphd — CHANGES_REQUESTED** [review]
Let's add a note to the Playwright wiki page about how your setup/login/projects stuff works in the config.

The rest looks great.

**Comment by Eakam1007** [comment]
I have updated the wiki with information about config, specifically the base URL, projects, and shared login state

**Review by humphd — APPROVED** [review]
So good!

**Review by sfrunza13 — APPROVED** [review]

**Pull request merged**
