### PR TITLE
Improve DNS Records table responsiveness

### PR DESCRIPTION
**Pull request by Eakam1007**
Part of #203 
This PR will handle the mobile screens, and further improvements can be made for the tablet screens in subsequent PRs

I initially went with hiding everything but the name and edit/delete buttons then realized that we had vertical space available for this. So, I have changed the DNS Record table to show data in one column for mobile screens. Here is an example for iPhone SE screen size (375w x 667h):

image

### CODE REVIEW

**Comment by humphd** [comment]
This is great, thank you for starting this.  Here's my initial feedback:

- The "Create new DNS Record+" button has too much text.  When we're narrow like this, can we shorten it?  I'm not sure what it should say: "DNS Record+" or "Create" or "New" etc
- I wonder if we should put all the buttons (info, copy, edit, delete) together in a row across the bottom vs. breaking them apart like this
- I also wonder if the Expiration Date should get treated like the other 3 text pieces, and make the text smaller, bold the title, etc.  Then the refresh button could join the other buttons along the bottom.

Some of this might be more work than you want to do here.

**Comment by humphd** [comment]
I think doing it in stages is a smart idea.  We don't need "perfect," only "improvement" over time.

**Comment by Eakam1007** [comment]
Alright, should I move the issue to post milestone 1.0 (remove the milestone)? The mobile screens could be handled here and I can do the tablet screens later

**Comment by humphd** [comment]
OK, sounds good.  Let us know when you want this reviewed.

**Comment by Eakam1007** [comment]
@humphd What do you think about this:

iPhoneSE (375w x 667h)
image

Galaxy Fold (280w x 653h): 
image

**Comment by humphd** [comment]
@Eakam1007 this is looking great.  I'd do the following:

- Add some margin to the top of the button container and use the full-width to spread them out more, so it's easier to "touch" them individually.
- Consider separating the DNS Record Name somehow from the rest of the info slightly, maybe add some margin on the bottom?  Maybe slightly larger font?

I think this is really close.  Amazing work!  I didn't think we'd get to this so fast.

**Comment by Eakam1007** [comment]
I have added some margin and made the buttons take up the entire space:

<details>
  <summary>iPhoneSE (375w x 667h)</summary>
  
  image
</details>

<details>
  <summary>Galaxy Fold (280w x 653h)</summary>
  
  image
</details>

<details>
  <summary>Expanding buttons video</summary>
  
  https://user-images.githubusercontent.com/67077705/232255023-99e64b24-65a2-4836-a250-f68c069ae658.mp4
</details>

**Comment by humphd** [comment]
A.M.A.Z.I.N.G!

**Review by humphd — APPROVED** [review]

**Comment by humphd** [comment]
@Eakam1007 can you update this to fix the merge conflict?  I'd like to get it into 1.0a.

**Review by humphd — APPROVED** [review]

**Review by SerpentBytes — APPROVED** [review]

**Pull request merged**
