### PR TITLE
Include all . characters in domain name

### LINKED ISSUE #359: Missing `.`s in domain display
In the Domains table, we are showing a user's domains, but they are missing all the `.`s except for the first one:

Screenshot 2023-03-16 at 4 34 31 PM

I have confirmed that this is not the case in the DB or Route53, it only happens in the UI.  I think it's probably due to how we're doing the UI to show the subdomain with a different colour.

cc @Myrfion

### PR DESCRIPTION
**Pull request by humphd**
Fixes #359.

Screenshot 2023-03-17 at 3 36 19 PM

### CODE REVIEW

**Review by Eakam1007 — DISMISSED** [review]

**Comment by humphd** [comment]
The approach to take with this will be changed by #377.  I might wait.

**Review by Ririio — APPROVED** [review]

**Comment by humphd** [comment]
I've re-done this using the new `subdomain` field in the db, with a slightly different approach.

**Comment by Myrfion** [comment]
Sorry, I just realized that I did the same thing as your PR does in #369 😢 I just didn't use `useUser`, but did it by doing something else in loader (your approach is way better, I just didn't think about this one. What would be a good strategy to resolve the issue that appeared?

**Comment by humphd** [comment]
@Myrfion why don't you take what I did in this PR, and do it in yours.  Then you can close this PR when it's done.

**Comment by Myrfion** [comment]
> @Myrfion why don't you take what I did in this PR, and do it in yours. Then you can close this PR when it's done.

Okay, updated my PR, closing this since #369 includes this PR's functionality

**Pull request closed without merging**
