### PR TITLE
fix: docker-build failure

### PR DESCRIPTION
**Pull request by SerpentBytes**
## Description
This PR could potentially fix the Docker build  [job](https://github.com/DevelopingSpace/starchart/actions/runs/4220103742/jobs/7326117425) failing due to Docker Engine not being able to find the imports located in the `/img` directory, as we are ignoring it in `.dockerignore`.

### CODE REVIEW

**Comment by SerpentBytes** [comment]
I have moved the image used by the project to `app/assets` and updated the import statement `certificate/loading.tsx`

**Review by humphd — CHANGES_REQUESTED** [review]
Can you move the `img/license` file too?  it goes with this file

**Review by humphd — APPROVED** [review]
Thanks for doing this, I totally missed it in my review before.

**Review by Ririio — APPROVED** [review]
I'm sorry I didn't know doing that could cause docker to fail

**Comment by SerpentBytes** [comment]
> I'm sorry I didn't know doing that could cause docker to fail

It happens. Part of the process.

**Pull request merged**
